### PR TITLE
Fix partial inf/nan matches

### PR DESCRIPTION
**Pull request by zoulasc**
Be careful with inf/nan conversions. We want to match only against
the precise [+-]{inf,infinity,nan} not words that start with those:
    
% awk 'BEGIN { print "nanotime" + 123 }'
nan
% awk 'BEGIN { print "microtime" + 123 }'
 123
 % awk 'BEGIN { print "-inftime" + 123 }'
 -inf

### CODE REVIEW

**Review by arnoldrobbins — COMMENTED** [review]
Your patch causes several test failures.  Please make sure the test suite runs.
If you're feeling adventurous, it'd be nice to disallow hex values in input data as well:

```sh
$ echo 0xDeadBeef | gawk '{ print $1 + 0}'
0
$ echo 0xDeadBeef | nawk '{ print $1 + 0}'
3735928559
```
Thanks!

**Comment by zoulasc** [comment]
I don't see the failures, can you please tell me which test(s) fail?

**Comment by arnoldrobbins** [comment]
> I don't see the failures, can you please tell me which test(s) fail?

Please see the attached file. I run on Ubuntu 18.04.  Thanks.
[test-results.txt](https://github.com/onetrueawk/awk/files/5244745/test-results.txt)

**Comment by wajap** [comment]
the proposal has a major issue with longer inputs. The example below shows
$ echo 'inform
123
inform' | awk '{print $0 + 0}'
0
123
123

Also when spaces are present the answer could be not what is expected :
$ echo 'inf    '  | awk '{print $0 + 0}'
0

$ echo '    inform'  | awk '{print $0 + 0}'
inf  

This change resolves it (compared was done to tran,c of the 201200806 master)

[diff_tran.txt](https://github.com/onetrueawk/awk/files/5478341/diff_tran.txt)

The test gave differences, but they are caused by the conversion of words starting with inf to inf.
Attached is the results (with modified Compare.tt to show the difference
[check_Modified_Compare.tt.txt](https://github.com/onetrueawk/awk/files/5478357/check_Modified_Compare.tt.txt)

**Comment by wajap** [comment]
sorry 201200806 should be 20200816

**Comment by arnoldrobbins** [comment]
I chose to do this differently, see PR #98 which I have merged. So I'm closing this PR. Thanks for the contribution.

**Pull request closed without merging**
