### PR TITLE
small fixes

### PR DESCRIPTION
**Pull request by zoulasc**
- some more const and static
- inputFS is now dynamically allocated
- account for lineno when putting back characters
- add an EMPTY variable (the empty string) to assign to writable string pointers.

### CODE REVIEW

**Comment by zoulasc** [comment]
It is for -Wwrite-strings. After that is merged there are only 2 instances left to be fixed one of them can re-use EMPTY. The other is fs = "(regexpr)". I am picking NetBSD changes so I can reduce the number of diffs. Will use staging in the future.

**Comment by zoulasc** [comment]
So would you like me to move it to staging?

**Comment by arnoldrobbins** [comment]
> So would you like me to move it to staging?

Yes, please. That would help. Also I've been busy with $REAL_LIFE.  Thanks.

**Comment by zoulasc** [comment]
moved to staging.

**Pull request closed without merging**
